### ISSUE TITLE
App is broken

### ISSUE THREAD

**Issue by mmkostov** [d-ivashchuk/cascade#7]
When navigating around and trying to login nothing happens and this error shows up:
`Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
    at path
    at svg
    at li
    at ul
    at div
    at div
    at div
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:241:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:338:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:356:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:241:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:338:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:356:11)
    at Lazy
    at main
    at div
    at Identification (webpack-internal:///(ssr)/./src/components/providers/index.tsx:33:27)
    at Provider (webpack-internal:///(ssr)/./node_modules/.pnpm/@radix-ui+react-context@1.0.1_@types+react@18.2.62_react@18.2.0/node_modules/@radix-ui/react-context/dist/index.mjs:48:28)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (webpack-internal:///(ssr)/./node_modules/.pnpm/@radix-ui+react-tooltip@1.0.7_@types+react-dom@18.2.22_@types+react@18.2.62_react-dom@18.2.0_react@18.2.0/node_modules/@radix-ui/react-tooltip/dist/index.mjs:73:29)
    at PostHogProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/posthog-js@1.116.6/node_modules/posthog-js/react/dist/esm/index.js:21:23)
    at PlausibleProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/next-plausible@3.12.0_next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next-plausible/dist/index.esm.js:147:13)
    at SessionProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/next-auth@4.24.7_next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/react/index.js:454:24)
    at TRPCProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/@trpc+react-query@11.0.0-rc.340_@tanstack+react-query@5.28.6_@trpc+client@11.0.0-rc.340_@trpc_jgvchpm7etln3ma7ahrr6tddsa/node_modules/@trpc/react-query/dist/shared/hooks/createHooksInternal.mjs:42:17)
    at QueryClientProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/@tanstack+react-query@5.28.6_react@18.2.0/node_modules/@tanstack/react-query/build/modern/QueryClientProvider.js:25:30)
    at TRPCReactProvider (webpack-internal:///(ssr)/./src/trpc/react.tsx:49:73)
    at O (webpack-internal:///(ssr)/./node_modules/.pnpm/next-themes@0.3.0_react-dom@18.2.0_react@18.2.0/node_modules/next-themes/dist/index.mjs:23:24)
    at z (webpack-internal:///(ssr)/./node_modules/.pnpm/next-themes@0.3.0_react-dom@18.2.0_react@18.2.0/node_modules/next-themes/dist/index.mjs:18:48)
    at ThemeProvider (webpack-internal:///(ssr)/./src/components/providers/theme-provider.tsx:13:26)
    at Providers (webpack-internal:///(ssr)/./src/components/providers/index.tsx:54:22)
    at Suspense
    at body
    at html
    at RootLayout (webpack-internal:///(ssr)/./src/app/layout.tsx:29:23)
    at Lazy
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:84:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:308:11)
    at Router (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:177:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:114:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:521:13)
    at Lazy
    at Lazy
    at rw (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:15737)
    at rw (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:15737)
    at ServerInsertedHTMLProvider (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:21384)
Warning: Invalid DOM property `clip-rule`. Did you mean `clipRule`?
    at path
    at svg
    at li
    at ul
    at div
    at div
    at div
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:241:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:338:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:356:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:241:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:338:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/layout-router.js:356:11)
    at Lazy
    at main
    at div
    at Identification (webpack-internal:///(ssr)/./src/components/providers/index.tsx:33:27)
    at Provider (webpack-internal:///(ssr)/./node_modules/.pnpm/@radix-ui+react-context@1.0.1_@types+react@18.2.62_react@18.2.0/node_modules/@radix-ui/react-context/dist/index.mjs:48:28)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (webpack-internal:///(ssr)/./node_modules/.pnpm/@radix-ui+react-tooltip@1.0.7_@types+react-dom@18.2.22_@types+react@18.2.62_react-dom@18.2.0_react@18.2.0/node_modules/@radix-ui/react-tooltip/dist/index.mjs:73:29)
    at PostHogProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/posthog-js@1.116.6/node_modules/posthog-js/react/dist/esm/index.js:21:23)
    at PlausibleProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/next-plausible@3.12.0_next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next-plausible/dist/index.esm.js:147:13)
    at SessionProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/next-auth@4.24.7_next@14.1.4_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/react/index.js:454:24)
    at TRPCProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/@trpc+react-query@11.0.0-rc.340_@tanstack+react-query@5.28.6_@trpc+client@11.0.0-rc.340_@trpc_jgvchpm7etln3ma7ahrr6tddsa/node_modules/@trpc/react-query/dist/shared/hooks/createHooksInternal.mjs:42:17)
    at QueryClientProvider (webpack-internal:///(ssr)/./node_modules/.pnpm/@tanstack+react-query@5.28.6_react@18.2.0/node_modules/@tanstack/react-query/build/modern/QueryClientProvider.js:25:30)
    at TRPCReactProvider (webpack-internal:///(ssr)/./src/trpc/react.tsx:49:73)
    at O (webpack-internal:///(ssr)/./node_modules/.pnpm/next-themes@0.3.0_react-dom@18.2.0_react@18.2.0/node_modules/next-themes/dist/index.mjs:23:24)
    at z (webpack-internal:///(ssr)/./node_modules/.pnpm/next-themes@0.3.0_react-dom@18.2.0_react@18.2.0/node_modules/next-themes/dist/index.mjs:18:48)
    at ThemeProvider (webpack-internal:///(ssr)/./src/components/providers/theme-provider.tsx:13:26)
    at Providers (webpack-internal:///(ssr)/./src/components/providers/index.tsx:54:22)
    at Suspense
    at body
    at html
    at RootLayout (webpack-internal:///(ssr)/./src/app/layout.tsx:29:23)
    at Lazy
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:84:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:308:11)
    at Router (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:177:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:114:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:521:13)
    at Lazy
    at Lazy
    at rw (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:15737)
    at rw (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:15737)
    at ServerInsertedHTMLProvider (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/next@14.1.4_@babel+core@7.24.3_@opentelemetry+api@1.8.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:21384)`
    
Also, when trying to populate test users this shows up:
`
Environment variables loaded from .env
Running seed command `tsx prisma/seed.ts` ...
PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation in
/home/martin/Documents/Code/Projects/cascade/prisma/seed.ts:18:19

  15 const planId = addPlan ? Math.floor(Math.random() * 4) + 1 : null;
  16 
  17 userPromises.push(
→ 18   prisma.user.create(
Foreign key constraint failed on the field: `User_planId_fkey (index)`
    at In.handleRequestError (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:6877)
    at In.handleAndLogRequestError (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async Promise.all (index 0)
    at main (/home/martin/Documents/Code/Projects/cascade/prisma/seed.ts:32:3) {
  code: 'P2003',
  clientVersion: '5.14.0',
  meta: { modelName: 'User', field_name: 'User_planId_fkey (index)' }
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: tsx prisma/seed.ts
martin@opensuse:~/Documents/Code/Projects/cascade> npx prisma db seed
Environment variables loaded from .env
Running seed command `tsx prisma/seed.ts` ...
PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation in
/home/martin/Documents/Code/Projects/cascade/prisma/seed.ts:42:19

  39   : null;
  40 
  41 userPromises.push(
→ 42   prisma.user.create(
Unique constraint failed on the fields: (`id`)
    at In.handleRequestError (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:6877)
    at In.handleAndLogRequestError (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/home/martin/Documents/Code/Projects/cascade/node_modules/.pnpm/@prisma+client@5.14.0_prisma@5.14.0/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async Promise.all (index 32)
    at main (/home/martin/Documents/Code/Projects/cascade/prisma/seed.ts:55:3) {
  code: 'P2002',
  clientVersion: '5.14.0',
  meta: { modelName: 'User', target: [ 'id' ] }
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: tsx prisma/seed.ts
`

**Comment by d-ivashchuk** [comment]
Hey! what steps did you take to run the app? did you follow the setup instructions?

https://stackonfire.mintlify.app/quickstart

**Comment by HeroSony** [comment]
I got that error too. already follow https://stackonfire.mintlify.app/quickstart and start `pnpm install && pnpm run dev
`
`

**Comment by OpenSourceAnarchist** [comment]
@HeroSony The solution to that error at least (and your #9) is to replace the seed.ts file with something like this (ensures unique id values with a new db each time and a seeded plan table):

```
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  // Clear previous data if any.
  await prisma.user.deleteMany();
  await prisma.plan.deleteMany();

  // Seed the plans first
  const plansData = [
    { name: 'Free Plan', lemonSqueezyVariantId: 'free_plan' },
    { name: 'Basic Plan', lemonSqueezyVariantId: 'basic_plan' },
    { name: 'Premium Plan', lemonSqueezyVariantId: 'premium_plan' },
    { name: 'Enterprise Plan', lemonSqueezyVariantId: 'enterprise_plan' }
  ];

  const plans = await Promise.all(
    plansData.map((plan) => prisma.plan.create({ data: plan }))
  );
  const planIds = plans.map((p) => p.id);

  // Create 100 users, some with a random plan
  const userPromises = [];
  for (let i = 1; i <= 100; i++) {
    const name = `User ${i}`;
    const email = `user${i}@example.com`;
    // Randomly decide whether to assign a plan (75% chance)
    const addPlan = Math.random() > 0.25;
    const planId = addPlan ? planIds[Math.floor(Math.random() * planIds.length)] : null;

    userPromises.push(
      prisma.user.create({
        data: {
          id: `DEMO_USER_${i}`,
          name,
          email,
          ...(planId && { planId }), // Include planId only if it exists
        },
      })
    );
  }

  await Promise.all(userPromises);
  console.log("100 users created, some with random plans.");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });

```
